# -*- coding: utf-8 -*-
"""graf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVftZzrqBKIT4fddzlA8crJKlfnBVCg4
"""

import csv
import matplotlib.pyplot as plt


x = []
y = []
with open('subscribe.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Пропускаем заголовки столбцов
    for row in reader:
        x.append((row[0]))  # Считываем значения для оси X
        y.append(int(row[1]))  # Считываем значения для оси Y

colors = ['darksalmon', 'yellow', 'pink', 'coral']

plt.barh(x, y, color=colors)

plt.xlabel('Кол-во сериалов')
plt.ylabel('Типы подписокв')
plt.title('Доступные сериалы по подписке')

plt.show()





x = []
y = []
with open('export.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  
    for row in reader:
        x.append((row[0]))  
        y.append(int(row[1]))  


plt.figure(figsize=(8, 10))
colors = ['darksalmon', 'yellow', 'pink', 'coral']

plt.barh(x, y, color=colors)

plt.xlabel('Год')
plt.ylabel('Кол-во фильмов')
plt.title('Кол-во снятых фильмов в году')

plt.show()




x = []
y = []
with open('u.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  
    for row in reader:
        x.append((row[0]))  
        y.append(int(row[1]))  

plt.figure(figsize=(8, 22))
colors = ['darksalmon', 'yellow', 'pink', 'coral']

plt.barh(x, y, color=colors)

plt.xlabel('Кол-во отзывов')
plt.ylabel('Имя пользователя')
plt.title('Кол-во оставленных отзывов')

plt.show()




x = []
y = []
with open('genre.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader) 
    for row in reader:
        x.append((row[0]))  
        y.append(int(row[1]))  


colors = ['darksalmon', 'yellow', 'pink', 'coral']

plt.barh(x, y, color=colors)


plt.xlabel('Кол-во сериалов')
plt.ylabel('Название жанра')
plt.title('Кол-во сериалов в каждом жанре')

plt.show()
